### PR TITLE
rmv file lock #104 & epoch smooth thread #83 #105 & limit cpu #115

### PR DESCRIPTION
**Pull request by xiaoch05**
该MR主要解决下面几个问题
1、删除文件锁，使用内存锁管理请求和生成ethashproof磁盘数据冲突
2、使用独立的协程管理ethashproof磁盘数据（生成和清理）
3、根据当前最高区块提前自动生成ethash文件并限制CPU占用率，平滑处理用户请求
4、删除所有默认存放目录，将目录配置统一提到go代码入口处，后续进一步放到文件配置中

### CODE REVIEW

**Comment by HackFisher** [comment]
@xiaoch05 The CI seems cancelled due to timeout, would you help check the reason, or help fix the CI?

**Comment by xiaoch05** [comment]
> @xiaoch05 The CI seems cancelled due to timeout, would you help check the reason, or help fix the CI?

Yes, the reason is that CPU is limited by 3 cores(default number) used by ethashproof in this PR. So it takes a longer time to execute the command.(the epoch DAG file is generated at the beginning of the epoch for smooth, in the testcase, also it request epoch at the beginning)
So there are two ways. First, cancel limit CPU usage currently. Second, the test case relaxes the executing time for this ethashproof command.

**Comment by HackFisher** [comment]
> > @xiaoch05 The CI seems cancelled due to timeout, would you help check the reason, or help fix the CI?
> 
> Yes, the reason is that CPU is limited by 3 cores(default number) used by ethashproof in this PR. So it takes a longer time to execute the command.(the epoch DAG file is generated at the beginning of the epoch for smooth, in the testcase, also it request epoch at the beginning)
> So there are two ways. First, cancel limit CPU usage currently. Second, the test case relaxes the executing time for this ethashproof command.

I'm afraid it is not easy to cancel limit CPU usage

we can try relaxing the executing time first, or comment test cases out if you can run the test cases locally.

**Comment by xiaoch05** [comment]
> > > @xiaoch05 The CI seems cancelled due to timeout, would you help check the reason, or help fix the CI?
> > 
> > 
> > Yes, the reason is that CPU is limited by 3 cores(default number) used by ethashproof in this PR. So it takes a longer time to execute the command.(the epoch DAG file is generated at the beginning of the epoch for smooth, in the testcase, also it request epoch at the beginning)
> > So there are two ways. First, cancel limit CPU usage currently. Second, the test case relaxes the executing time for this ethashproof command.
> 
> I'm afraid it is not easy to cancel limit CPU usage
> 
> we can try relaxing the executing time first, or comment test cases out if you can run the test cases locally.

ok, I have a try

**Comment by xiaoch05** [comment]
> > > @xiaoch05 The CI seems cancelled due to timeout, would you help check the reason, or help fix the CI?
> > 
> > 
> > Yes, the reason is that CPU is limited by 3 cores(default number) used by ethashproof in this PR. So it takes a longer time to execute the command.(the epoch DAG file is generated at the beginning of the epoch for smooth, in the testcase, also it request epoch at the beginning)
> > So there are two ways. First, cancel limit CPU usage currently. Second, the test case relaxes the executing time for this ethashproof command.
> 
> I'm afraid it is not easy to cancel limit CPU usage
> 
> we can try relaxing the executing time first, or comment test cases out if you can run the test cases locally.

I have recheck the problem, sorry it’s not caused by CPU usage limitation.
The ethashproof command executed so long, so I thought it's caused by this limitation.
The real reason is that. In test case, the new added goroutine has not been started.
The problem is repaired by commit https://github.com/darwinia-network/shadow/pull/126/commits/1edadf9a975ae13b5014a51d8d3b49321e51e17c

**Comment by HackFisher** [comment]
@wuminzhe Please help review this pull request, thanks

**Review by wuminzhe — APPROVED** [review]

**Pull request merged**
