### PR TITLE
Multistore

### PR DESCRIPTION
**Pull request by wuminzhe**

### CODE REVIEW

**Comment by HackFisher** [comment]
@wuminzhe There are some conflicts require resolve.

**Comment by HackFisher** [comment]
@xiaoch05 Please help review this pul request.

**Comment by xiaoch05** [comment]
this pr has so many files moving, can you separate processing the file moving? otherwise, I can't see clearly what's modified. @wuminzhe , and also there are many conflicts need to be merged.

**Comment by xiaoch05** [comment]
@wuminzhe I suggest you recreate a branch to commit the modification. Because this PR has some commits submitted 22 days ago, which had been merged to master before.
I got the same problem, the reason is that you are using a local branch that deleted on remote, and you pushed it again.

**Comment by HackFisher** [comment]
If not able to resolve these conflicts in one PR, please split them into several pull requests according to features/refactors.

Looking forward to merge them.

**Comment by wuminzhe** [comment]
Ok, I will split this PR to smaller PRs.

**Comment by HackFisher** [comment]
Re-create another pull request if there are changes not merged to master in this PR.

**Pull request closed without merging**
