### PR TITLE
Move the entry of shadow from Golang to Rust

### PR DESCRIPTION
**Pull request by clearloop**
## Desc

Here are lots of code in shadow service are as same as `darwinia-common`, for examples, eth primitives or MMR structure, rustify this repo and reduce duplicated code between `darwinia-common` and `shadow`.

## Steps

+ [x] MMR process
+ [x] Ethereum receipt
+ [x] Ethashproof
+ [x] HTTP Server
+ [x] Commands
+ [x] Fix the async error of tokio

### CODE REVIEW

**Comment by clearloop** [comment]
Remember removing the logs of commits 9b695ee to cf2cb23 while squash merging, they are mistakes of Github.

**Comment by HackFisher** [comment]
@wuminzhe Aki, could you help review this pull request?

**Comment by clearloop** [comment]
> @wuminzhe Aki, could you help review this pull request?

Wait a minute, more tests here.

**Comment by wuminzhe** [comment]
@HackFisher I will review it

**Review by wuminzhe — APPROVED** [review]

**Pull request merged**
