### PR TITLE
Xch import reduce

### PR DESCRIPTION
**Pull request by xiaoch05**

### CODE REVIEW

**Comment by HackFisher** [comment]
Did we check the canonical of the imported header, especially for those header from db(not from ancient files)?

**Comment by xiaoch05** [comment]
> Did we check the canonical of the imported header, especially for those header from db(not from ancient files)?

Yes, it used ReadCanonicalHash API, this API read the canonical header.
I should check whether this pr can read canonical header by a distance of 64 blocks from the highest block

**Comment by HackFisher** [comment]
Please add a check for the import path in cli parameters:

The path should end with "chaindata", in case of miss typing.

**Comment by xiaoch05** [comment]
> Did we check the canonical of the imported header, especially for those header from db(not from ancient files)?

I have confirmed that the headers read from both leveldb and ancient files are canonical, this means that the data this PR used is canonical. Also we make a 64 headers distance from the top header we read.
Different from the old one used go-ethereum directly. 
1. We ignore to check whether there are some conflicting data between ancient and database, this will never occur for shadow.
2. The old one will start a goroutine to move data from database to ancient files. This pr do nothing about this.
3. The old one read headers but this pr read hashes we need.
4. The old one gets hash bytes and transform them into strings in go, then deliver them to rust and re-transform them to bytes. This pr deliver hash bytes directly to rust.

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
